### PR TITLE
android: okhttp => 4.9

### PR DESCRIPTION
**Pull request by helllamer**
android: okhttp => 4.9
fetch.js: simplify error processing logic

### CODE REVIEW

**Comment by helllamer** [comment]
Looks like, repo changed owner or renamed.
@ebhsgit - Just for notification of new owner about this PR existence.

**Comment by ebhsgit** [comment]
Hi mate,

My fork is only intended for my own backup of the source code. I should be even or behind the upstream aporat/cordova-plugin-fetch

Please submit PR to upstream.

**Comment by helllamer** [comment]
@ebhsgit  Hmm, `aporat/cordova-plugin-fetch` is archived, and `README` contains link to your repository.
@aporat , could you give a comment about upstreaming of `cordova-plugin-fetch`?

**Comment by ebhsgit** [comment]
@aporat
I believe your README was accidentally as part of the last PR.

Please change your README to remove my repo url.

**Comment by aporat** [comment]
ah, no problem. I removed the link from the readme

**Pull request closed without merging**
